version: 0.2

phases:
  pre_build:
    commands:
      # Retrieve an authentication token and authenticate your Docker client to your registry
      - RESULT=$(aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URL)
      - echo $RESULT
  build:
    commands:
      # Build the Docker image
      - docker build -t streamlit-app:latest .
      - SHORT_VERSION=$(echo "$CODEBUILD_RESOLVED_SOURCE_VERSION" | cut -c 1-7)
      - docker tag streamlit-app:latest $REPOSITORY_URL:$SHORT_VERSION
      - docker tag streamlit-app:latest $REPOSITORY_URL:latest
      - echo $SHORT_VERSION
      - echo $REPOSITORY_URL
  
  post_build:
    commands:
      # Push docker images to ECR
      - docker push $REPOSITORY_URL:latest
      - docker push $REPOSITORY_URL:$SHORT_VERSION
      - printf '[{"name":"streamlit-app","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files: imagedefinitions.json